apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: customerapi 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customerapi 
    spec:
      containers:
        - name: customerapi 
          image: damon.azurecr.io/customerapi
          ports:
          - containerPort: 80